config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  include PgSearch::Model

  has_many :cells, dependent: :delete_all

  # Define search fields
  pg_search_scope :search_board,
                  against: { name: 'A', creator_email: 'B' },
                  using: {
                    tsearch: {
                      dictionary: 'english', tsvector_column: 'searchable'
                    }
                  }
end

app/models/cell.rb
class Cell < ApplicationRecord
    belongs_to :board

    validates :row, :column, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/concerns/board_contract.rb
class BoardContract < Dry::Validation::Contract
  params do
    required(:width).filled(:integer)
    required(:height).value(:integer)
    required(:num_mimes).value(:integer)
    required(:name).value(:string)
    required(:creator_email).value(:string)
  end

  rule(:width) do
    key.failure('must be greater than zero') if value <= 0
  end

  rule(:height) do
    key.failure('must be greater than zero') if value <= 0
  end

  rule(:num_mimes) do
    key.failure('must be greater than or equal to zero') if value < 0
  end

  rule(:num_mimes, :width,  :height) do
    available_num_mimes = values[:width] * values[:height]
    key.failure("must be less than or equal to #{available_num_mimes}") if values[:num_mimes] > available_num_mimes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @search = params[:search]
    if @search.present?
      scope = Board.search_board(@search)
    else
      scope = Board.all
    end

    @pagy, @boards = pagy(scope.order(created_at: :desc))
  end

  def new
    @board = Board.new
  end

  def create
    resolve("boards.create").call(board_params.to_h) do |m|
      m.success do |board|
        return redirect_to board, notice: 'Board was successfully created.'
      end

      m.failure do |failure|
        flash.now[:alert] = failure.errors(full: true).to_h.values.join(',')
        @board = Board.new(board_params)
        render :new
      end
    end
  rescue StandardError => error
    flash.now[:alert] = error
    @board = Board.new(board_params)
    render :new
  end

  def show
    @board = Board.includes(:cells).find(params[:id])
  end

  def board_params
    params.require(:board).permit(:height, :width, :name, :creator_email, :num_mimes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @boards = Board.order(created_at: :desc).limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/boards/index.html.erb
<div class="board-list">
  <div class="pb-3 pt-3">
    <h3>All mimesweeper boards</h5>
  </div>
  <div class="add-new-board pb-3">
    <a class="btn btn-link" href="/" role="button">Back to home</a>
    <a class="btn btn-link" href="/boards/new" role="button">Generate new board</a>
  </div>

  <%= render "shared/search_form" %>

  <div class="list-group">
    <% @boards.each do |board| %>
      <%= render partial: 'shared/board_card', locals: { board: board } %>
    <% end %>
  </div>
  <div class="pagination mt-3">
    <%== pagy_bootstrap_nav(@pagy, link_extra: 'data-action="hello#world"') %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="add-new-board pt-3 pb-3">
  <a class="btn btn-link" href="/" role="button">Back to home</a>
  <a class="btn btn-link" href="/boards" role="button">View all boards</a>
</div>

<div class="mb-3 mt-3">
  <h2>Mime Sweeper board generator</h2>
</div>

<%= form_for @board, class: "form-horizontal board-form" do |form| %>
  <div class="form-group mb-3">
    <%= form.label :name, 'Board Name', class: "form-label col-sm-4" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>
  </div>

  <div class="form-group mb-3">
    <%= form.label :height, class: "form-label col-sm-4" %>
    <div class="col-sm-10">
      <%= form.number_field :height, class: "form-control", required: true, min: 1, step: "1" %>
    </div>
  </div>
  <div class="form-group mb-3">
    <%= form.label :width, class: "form-label col-sm-4" %>
    <div class="col-sm-10">
      <%= form.number_field :width, class: "form-control", required: true, min: 1, step: "1" %>
    </div>
  </div>

  <div class="form-group mb-3">
    <%= form.label :num_mimes, 'Number of mimes', class: "form-label col-sm-4" %>
    <div class="col-sm-10">
      <%= form.number_field :num_mimes, class: "form-control", required: true, min: 0, step: "1" %>
    </div>
  </div>

  <div class="form-group mb-3">
    <%= form.label :creator_email, 'Your Email', class: "form-label col-sm-4" %>
    <div class="col-sm-10">
      <%= form.email_field :creator_email, class: "form-control", required: true, pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" %>
    </div>
  </div>

  <div class="form-group mb-3">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit "Generate Board", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/boards/show.html.erb
<div class="board-page">
  <div class="add-new-board pt-3">
    <a class="btn btn-outline-primary" href="/boards/new" role="button">Generate new board</a>
    <a class="btn btn-outline-primary" href="/boards" role="button">View all boards</a>
  </div>
  <div class="pt-4 pb-3">
    <h1><%= @board.name %></h1>
    <span>Size: <%= @board.width %> x <%= @board.height%> </span>
  </div>

  <div class="board-details">
    <table class="mimesweepers">
      <% @board.cells.order(:row, :column).group_by(&:row).each do |_, row| %>
        <tr>
          <% row.each do |cell| %>
            <td>
              <% if cell.is_mime %>
                <i class="fa-sharp fa-solid fa-bomb"></i>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<div class="board-list">
  <div class="mb-3 mt-4">
    <h3>Recent mimesweeper boards</h5>
  </div>
  <div class="add-new-board pb-3">
    <a class="btn btn-primary" href="/boards/new" role="button">Generate new board</a>
  </div>
  <div class="list-group">
    <% @boards.each do |board| %>
      <%= render partial: 'shared/board_card', locals: { board: board } %>
    <% end %>
  </div>
  <div class="add-new-board pt-3">
    <a class="btn btn-link" href="/boards" role="button">View all generated boards</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mimesweeper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% flash.each do |type, msg| %>
      <div class="alert <%= type == 'alert' ? 'alert-danger' : 'alert-primary' %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_board_card.html.erb
<div class="list-group-item list-group-item-action" aria-current="true">
  <div class="d-flex w-100 justify-content-between">
    <%= link_to(board_url(board), html_options = {}) do %>
      <h5 class="mb-1">
        <%= board.name %>
      </h5>
    <% end %>
    <small><%= time_ago_in_words(board.created_at) %></small>
  </div>
  <p class="mb-1">Made by: <%= board.creator_email %> </p>
</div>

app/views/shared/_search_form.html.erb
<div class="search-form pt-1 pb-5">
  <form>
    <div class="input-group flex-nowrap">
      <input type="text" name="search" class="form-control" placeholder="Search by name or creator email" aria-label="Search boards by name or creator email" aria-describedby="addon-wrapping", value = "<%= @search %>" />
      <button type="button" class="btn btn-primary">
        <i class="fas fa-search"></i>
      </button>
    </div>
  </form>
</div>